name: desejando_app
description: Desejando é um aplicativo desenvolvido para o compartilhamento de lista de wishs entre as pessoas.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.12
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_storage: ^10.2.15
  flutter_svg: ^1.0.3
  get: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0
  flutter_lints: ^1.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/Sarabun-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Sarabun-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sarabun-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sarabun-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sarabun-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Sarabun-Regular.ttf
          weight: 400
        - asset: assets/fonts/Sarabun-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/Sarabun-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sarabun-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sarabun-ThinItalic.ttf
          weight: 100
          style: italic