// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQy96jhaO4TrTI3Aepzqqz20EwI89Lu08',
    appId: '1:189883363296:web:7a7592ad0be08620fd8585',
    messagingSenderId: '189883363296',
    projectId: 'my-gift-ad6df',
    authDomain: 'my-gift-ad6df.firebaseapp.com',
    storageBucket: 'my-gift-ad6df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwo96e8_om5pHHOQPnJB6Wj0QmhFtgeEY',
    appId: '1:189883363296:android:e036058e64c30640fd8585',
    messagingSenderId: '189883363296',
    projectId: 'my-gift-ad6df',
    storageBucket: 'my-gift-ad6df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvA0v8W4S4zV7HKvtuISKqGgMgIphJGqk',
    appId: '1:189883363296:ios:443b10962e4ed2a6fd8585',
    messagingSenderId: '189883363296',
    projectId: 'my-gift-ad6df',
    storageBucket: 'my-gift-ad6df.appspot.com',
    androidClientId: '189883363296-60gsd45kshageuem0e29khimjtj2nms1.apps.googleusercontent.com',
    iosClientId: '189883363296-0k4m7piin3k716tk2avsn84fpva369a7.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielhainzenreder.myGiftApp',
  );
}
