name: Flutter_Tests

on:
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.6'
    - name: Flutter version
      run: flutter --version
    - name: Use variables
      run: |
        echo "variable: $FIREBASE_VARS"
      env:
        REPOSITORY_VAR: ${{ vars.FIREBASE_VARS }}
    - name: ${{ vars.API_KEY }}
      run: |
        echo "pinting: ${{ vars.API_KEY }}"
    - name: Pub get
      run: flutter pub get
    - name: Analyze
      run: flutter analyze
    - name: Run tests
      run: flutter test --coverage
    - name: Upload coverage to codecov
      run: curl -s https://codecov.io/bash
      shell: bash
